"""Individual adaptation to measured change, using own options and memories."""
from math import hypot
from .environment import climate_at

def update_adaptation(world):
    if world.tick%40:return
    for person in sorted(world.residents,key=lambda p:p.id):
        weather=climate_at(world,person.x,person.z)
        previous=person.memory.get("environment_history",[])
        sample={"tick":world.tick,"moisture":weather["moisture"],
                "temperature":weather["temperature"]}
        if previous:
            sample["change"]=round(weather["moisture"]-previous[-1]["moisture"],3)
        history=person.memory.setdefault("environment_history",[])
        history.append(sample)
        del history[:-8]
        # Attention changes but actions remain generated by the general planner.
        prefs=person.memory.setdefault("preferences",{})
        if len(history)>=2:
            swing=abs(history[-1]["moisture"]-history[-2]["moisture"])
            for need in ("food","health"):
                old=prefs.get(need,person.personality.get("caution",.5))
                prefs[need]=round(max(.05,min(.95,old+min(.02,swing*.04))),3)
